version: "3.8"
services:

    main:
    
        build:
            context: .
            dockerfile: Dockerfile

        env_file: .env
        environment:
            WAIT_HOSTS: mysql:3306
        restart: unless-stopped

        command: "php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        ports:
            - 8000:8000

        depends_on:
            - db

    db:
        image: mysql:8.2
        environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=pms

